required = ["github.com/jteeuwen/go-bindata"]

[[constraint]]
  name = "github.com/dgrijalva/jwt-go"
  version = "3.1.0"

[[constraint]]
  name = "github.com/gorilla/websocket"
  version = "1.2.0"

[[constraint]]
  branch = "master"
  name = "github.com/jmoiron/sqlx"

[[constraint]]
  name = "github.com/mattn/go-sqlite3"
  version = "1.6.0"

[[constraint]]
  branch = "master"
  name = "github.com/neelance/graphql-go"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"

[[constraint]]
  branch = "master"
  name = "golang.org/x/net"

[[constraint]]
  name = "gopkg.in/nicksrandall/dataloader.v5"
  version = "v5"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "v1.0.0"

[[constraint]]
  name = "github.com/satori/go.uuid"
  branch = "master"

[[constraint]]
  name = "github.com/lib/pq"
  branch = "master"